on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.repository == 'lumynou5/github-release-action'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: lumynou5/github-release-action@main
        with:
          token: ${{github.token}}
